# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
     version: '7.x'
     
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: ' --output $(Build.ArtifactStagingDirectory)' 
    zipAfterPublish: True
    workingDirectory: '$(Agent.BuildDirectory)/1/s/src/Contoso.Movies.Catalog'
  
- task: PublishBuildArtifacts@1
  inputs:
   TargetPath: '$(Build.ArtifactStagingDirectory)'
   ArtifactName: 'functionApp'