# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
     version: '7.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/ContosoMovies_Catalog.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: ' --output $(Build.ArtifactStagingDirectory)/funcStage' 
    projects: '**/ContosoMovies_Catalog.csproj'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/funcStage'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/func/build$(Build.BuildNumber).zip'

- task: PublishBuildArtifacts@1
  inputs:
   TargetPath: '$(Build.ArtifactStagingDirectory)/func/build$(Build.BuildNumber).zip'
   ArtifactName: 'drop'

- task: AzureFunctionApp@2
  inputs:
   connectedServiceNameARM: 'azure-demo-subscription'
   appType: 'functionAppLinux'
   appName: '20230814-alt-func'
   package: '$(System.ArtifactsDirectory)/**/*.zip'
   deploymentMethod: 'auto'
